services:
 
  web:
    image: soulaiamansoulb/websty
    build:
     
      context: .
    
      dockerfile: Dockerfile
      
    
 
    ports:
      - 5173:5173

   
    volumes:
   
      - .:/app
    
      - /app/node_modules